# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusrefgen', '0002_auto_20161023_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refgen',
            name='letter_subject',
            field=models.CharField(max_length=100),
        ),
    ]
