web:
    restart: always
    build: ./web/
    expose:
        - "8000"
    links:
        - postgres:postgres
    volumes:
        - ./web:/code
        - /code/cusrefgen/static
    env_file: .env
    command: /usr/local/bin/gunicorn orng.wsgi:application -w 2 -b :8000

apache:
    restart: always
    build: ./apache/
    ports:
        - "80:80"
    volumes:
        - /opt:/bitnami/apache
        - /www/static
        - ./apache/sites-enabled/vhosts:/bitnami/apache/conf/vhosts
    volumes_from:
        - web
    links:
        - web:web

postgres:
    restart: always
    image: postgres:latest
    ports:
        - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data/
