# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusrefgen', '0005_auto_20161101_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='refgen',
            name='ref_number',
            field=models.IntegerField(default=0),
        ),
    ]
