# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusrefgen', '0008_auto_20161102_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refgen',
            name='dispatch_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='refgen',
            name='org_units',
            field=models.CharField(choices=[(None, 'Select from dropdown'), ('AD/DI', 'Admin Services'), ('FIN/BO', 'Chief Finance Office'), ('CS/SEB', 'Corporate Services'), ('CC/KE', 'Customer Care'), ('DCO/SO', 'Data Centre Operations'), ('FIN/TO', 'Finance'), ('GMD/EA', 'Group Managing Director'), ('HR/TA', 'Human Capital Management'), ('IST/AS', 'Information Systems & Technology'), ('ME/TA', 'Media & Entertainment'), ('MKT/KS', 'Marketing'), ('NIU/GJ', 'Network Infrastructure Unit'), ('NSD/SO', 'Network Services Division'), ('PD/KJ', 'Product Development'), ('PM/TO', 'Program Management'), ('RD/SO', 'Research & Development'), ('SCM/RO', 'Supply Chain Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='refgen',
            name='ref_number',
            field=models.IntegerField(default=0),
        ),
    ]
