# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusrefgen', '0009_auto_20161123_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_ref_no', models.CharField(max_length=30)),
            ],
        ),
    ]
