# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusrefgen', '0010_refno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refno',
            name='generated_ref_no',
            field=models.CharField(max_length=60),
        ),
    ]
